spring.application.name=ecommerce
spring.security.user.name=user
spring.security.user.password=password


# SERVER
server.port=${SERVER_PORT:8080}

# DATABASE (MySQL)
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ecommerce_db}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

logging.level.org.springframework.security=DEBUG
spring.webflux.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}
spring.webflux.cors.allowed-methods=GET,POST,PUT,DELETE
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

secreteKey=${JWT_SECRET:YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYQ==}

razorpay.keyId=${RAZORPAY_KEY_ID:rzp_test_cDwJbY6QRF2zVw}
razorpay.keySecret=${RAZORPAY_KEY_SECRET:Ahsnni4WCgxLnEGh4NGjilXY}





